# Generated by Django 6.0 on 2026-01-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_articleimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleimage',
            options={'verbose_name': 'Article Image', 'verbose_name_plural': 'Article Images'},
        ),
    ]
