# Generated by Django 6.0 on 2026-01-06 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_articleimage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleimage',
            options={},
        ),
    ]
