# Generated by Django 6.0 on 2026-01-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_articleimage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='media/carousel/'),
        ),
        migrations.AddField(
            model_name='article',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='media/carousel/'),
        ),
        migrations.AddField(
            model_name='article',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='media/carousel/'),
        ),
        migrations.AddField(
            model_name='article',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='media/carousel/'),
        ),
        migrations.AddField(
            model_name='article',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='media/carousel/'),
        ),
        migrations.DeleteModel(
            name='ArticleImage',
        ),
    ]
