# Generated by Django 6.0 on 2026-01-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_image_1_article_image_2_article_image_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
